- hosts: localhost
  become: yes

  tasks:
    - name: Töröld a régi Angular buildet
      file:
        path: /var/www/html/angular-app/
        state: absent

    - name: Hozd létre újra az app könyvtárát
      file:
        path: /var/www/html/angular-app/
        state: directory

    - name: Másold át az Angular build fájljait
      copy:
        src: ./dist/
        dest: /var/www/html/angular-app/
